name: pipe
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - accelerate
  - ipykernel
  - ipywidgets
  - matplotlib
  - numpy
  - pandas
  - pyarrow
  - pytest
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - tqdm
  - transformers
  - pip
  - pip:
      - bitsandbytes
      - minicons
